services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - server-network
      - sensor-network
      - default
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
  proxy:
    image: meteo-rabbitmq/proxy
    build:
      context: .
      dockerfile: proxy/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - INTERVAL=2000
      - RABBITMQ_ADDRESS=amqp://rabbitmq:5672
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
    networks:
      - server-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - server-network
  server:
    image: meteo-rabbitmq/server
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_ADDRESS=amqp://rabbitmq:5672
      - REDIS_ADDRESS=redis://redis:6379
      - LOG_LEVEL=debug
    networks:
      - server-network
  air-quality-sensor:
    image: meteo-rabbitmq/sensor
    build:
      context: .
      dockerfile: sensor/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - INTERVAL=1000
      - SENSOR_TYPE=air_quality
      - RABBITMQ_ADDRESS=amqp://rabbitmq:5672
      - LOG_LEVEL=debug
    networks:
      - sensor-network
  pollution-sensor:
    image: meteo-rabbitmq/sensor
    build:
      context: .
      dockerfile: sensor/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - INTERVAL=1000
      - SENSOR_TYPE=pollution
      - RABBITMQ_ADDRESS=amqp://rabbitmq:5672
      - LOG_LEVEL=debug
    networks:
      - sensor-network
networks:
  server-network:
    driver: bridge
  sensor-network:
    driver: bridge
